### ISSUE TITLE
Add @token_required decorator to all the routes

### ISSUE THREAD

**Issue by bbhupen** [bbhupen/Farmer-Support-Backend-API#6]
Just need to add @token_required decorator to all the available routes in app.py

**Comment by bbhupen** [comment]
hey @Preet-taparia 

this issue is related to #2 

just need to add the decorator. You might take up this issue if you want, as #5 was done by you??

**Comment by Esh07** [comment]
If this task is still unassigned, may I have the opportunity to give it a try?

 Thanks

**Comment by Preet-taparia** [comment]
will do it

**Comment by Preet-taparia** [comment]
Should home have the decorator or not?

**Comment by bbhupen** [comment]
> Should home have the decorator or not?

nope

**Comment by bbhupen** [comment]
> If this task is still unassigned, may I have the opportunity to give it a try?
> 
> Thanks

Hey @Esh07 thank you for this, btw @Preet-taparia was already working on this issue, so. Meanwhile you can check the codebase and look for any other issue.

Thanks

**Comment by Esh07** [comment]
Hi @bbhupen, I’m sorry for the confusion. I didn’t know that @Preet-taparia was already working on this issue. I hope I didn’t cause any trouble or inconvenience. I will check the codebase and look for any other issue that I can help with.

Thanks for the clarification
