### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by Preet-taparia** [bbhupen/Farmer-Support-Backend-API#8]
This documentation should contain a set of guidelines to help others during the contribution process.

**Comment by bbhupen** [comment]
@Preet-taparia added the hacktoberfest necessary labels, so that it'll get accepted

**Comment by Vasanthavel124** [comment]
can you assign this to me?

**Comment by bbhupen** [comment]
@Vasanthavel124 

@Preet-taparia was already working on it.
